### ISSUE TITLE
Add list of top level collections that are being crawled

### ISSUE THREAD

**Issue by jronallo** [saracarl/Pontiiif#7]
It would be nice to have a list of links to the collections that Pontiiif is currently crawling and indexing.

As a user, I want to know what collections are being crawled, so that I can know what to expect to see in search results.

As a publisher of a collection and manifests, I want to know whether my content is or will be crawled, so that I can know whether to submit my collection.

It could get more involved and featureful than this, but starting out with just a list mirroring back the list of collections you use as a starting point for crawling would be a great start.

**Comment by benwbrum** [comment]
This has been built and deployed in version 1.1 of Pontiiif.
